spring:
  profiles:
    active: local
  session:
    store-type: redis
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxxxxx
    username: xxxxxx
    password: xxxxxxx
  application:
    name: xy-ai-code-generator-backend
server:
  port: 8001
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.xy.aicodegenerator.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# 配置日志级别以打印MyBatis-Flex的SQL语句
logging:
  level:
    com.xy.aicodegenerator.mapper: debug